# Copyright (2024) Beijing Volcano Engine Technology Ltd.
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "common.names.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
  labels: {{- include "common.labels.standard" . | nindent 4}}
stringData:
  config.json: |
    {
      "volc_host": {{ .Values.cluster.volcHost | quote }},
      "access_key": {{ .Values.cluster.ak | quote }},
      "secret_key": {{ .Values.cluster.sk | quote }},
      "region": {{ .Values.cluster.region | quote }},
      "webhook_name": {{ .Values.deploy.containerSettings.webhookName | quote }},
      "webhook_cert_dir": {{ .Values.deploy.containerSettings.certDir | quote }},
      "webhook_port": {{ .Values.deploy.containerSettings.webhookPort | quote }},
      "secret_name": {{ .Values.deploy.containerSettings.secretName | quote }},
      "secret_namespace": {{ .Values.deploy.containerSettings.secretNamespace | quote }},
      "service_name": {{ include "common.names.fullname" . | quote }},
      "service_namespace": {{ .Release.Namespace | quote }}
    }
type: Opaque